languageCode = "en-us"
title = "Sebastian's Blog"
baseurl = "http://sebastianporto.com/blog"
theme = "hemingway2"

[params]
[params.highlight]
style = "github"
languages = ["javascript", "elm"]

[[params.social]]
url = "https://github.com/sporto"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/sebasporto"
fa_icon = "fa-twitter"
